---
- name: Install ZFS packages
  community.general.pacman:
    name:
      - zfs-utils
    state: "{{ package_state }}"

- name: Load ZFS kernel module
  modprobe:
    name: zfs
    state: present

- name: Enable ZFS services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - zfs-import-cache.service
    - zfs-import.target
    - zfs-mount.service
    - zfs.target

- name: Check if ZFS pools exist
  command: zpool list {{ item.name }}
  register: zpool_checks
  changed_when: false
  failed_when: false
  loop: "{{ zfs_pools }}"
  when: zfs_pools is defined

- name: Import ZFS pools
  command: zpool import {{ item.item.name }}
  when: 
    - zfs_pools is defined
    - item.rc != 0
  loop: "{{ zpool_checks.results }}"
  loop_control:
    label: "{{ item.item.name }}"

- name: Create ZFS datasets
  zfs:
    name: "{{ item.0.name }}/{{ item.1 }}"
    state: present
  with_nested:
    - "{{ zfs_pools }}"
    - "{{ item.0.datasets | default([]) }}"
  when: 
    - zfs_pools is defined
    - item.0.datasets is defined
