---
- name: Install Cockpit System packages
  community.general.pacman:
    name:
      - cockpit
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-files
      - cockpit-machines
      - cockpit-podman
      - udisks2
    state: present

- name: Install Cockpit AUR packages
  kewlfft.aur.aur:
    name:
      - cockpit-file-sharing
      - cockpit-navigator
      - cockpit-zfs-manager
      - cockpit-sensors
      - udisks2
    use: paru
  become: yes
  become_user: aur_builder
  when: install_aur_packages | default(false)

- name: Enable and start Cockpit socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Configure firewall for Cockpit
  community.general.ufw:
    rule: allow
    port: '9090'
    proto: tcp
    comment: Cockpit web interface
