---
- name: Install Cockpit System packages
  community.general.pacman:
    name:
      - cockpit
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-files
      - cockpit-machines
      - cockpit-podman
      - udisks2
    state: "{{ package_state }}"

- name: Install Cockpit AUR packages
  kewlfft.aur.aur:
    name:
      - cockpit-file-sharing
      - cockpit-navigator
      - cockpit-zfs-manager
      - cockpit-sensors
      - udisks2
    use: paru
    state: "{{ package_state }}"
  become: yes
  become_user: aur_builder
  when: install_aur_packages | default(false)

- name: Enable and start Cockpit socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Configure firewall for Cockpit
  community.general.ufw:
    rule: allow
    port: '9090'
    proto: tcp
    comment: Cockpit web interface

- name: Ensure /etc/cockpit/zfs directory exists
  ansible.builtin.file:
    path: /etc/cockpit/zfs
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install cockpit-zfs-manager config if it does not exist
  ansible.builtin.copy:
    src: cockpit-zfs-config.json
    dest: /etc/cockpit/zfs/config.json
    owner: root
    group: root
    mode: '0644'
    force: no

- name: Ensure /etc/cockpit/zfs/shares directory exists
  ansible.builtin.file:
    path: /etc/cockpit/zfs/shares
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install cockpit-zfs-manager shares config if it does not exist
  ansible.builtin.copy:
    src: cockpit-zfs-shares.conf
    dest: /etc/cockpit/zfs/shares.conf
    owner: root
    group: root
    mode: '0644'
    force: no

- name: Install cockpit-zfs-manager example share config if it does not exist
  ansible.builtin.copy:
    src: cockpit-zfs-shares-pool0_export.conf
    dest: /etc/cockpit/zfs/shares/pool0_export-share.conf
    owner: root
    group: root
    mode: '0644'
    force: no

