---
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
  - name: community.libvirt
    version: ">=1.3.0"
  - name: kewlfft.aur
    version: ">=0.13.0,<0.14"
