---
- name: Install libvirt and KVM packages
  community.general.pacman:
    name:
      - libvirt
      - qemu-full
      - virt-install
      - virt-manager
      - virt-viewer
      - dnsmasq
      - ebtables
      - bridge-utils
      - openbsd-netcat
      - dmidecode
    state: present

- name: Add users to libvirt group
  user:
    name: "{{ item }}"
    groups: libvirt
    append: yes
  loop: "{{ virt_users }}"

- name: Create VM storage directory on ZFS
  file:
    path: /tank/virt-images
    state: directory
    mode: '0755'

- name: Configure libvirt storage pool for VMs
  blockinfile:
    path: /etc/libvirt/storage/virt-images.xml
    create: yes
    mode: '0644'
    block: |
      <pool type='dir'>
        <name>virt-images</name>
        <source>
        </source>
        <target>
          <path>/tank/virt-images</path>
          <permissions>
            <mode>0755</mode>
          </permissions>
        </target>
      </pool>
  notify: restart libvirtd

- name: Enable and start libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Enable libvirt default network
  command: virsh net-autostart default
  changed_when: false
  failed_when: false

- name: Start libvirt default network
  command: virsh net-start default
  changed_when: false
  failed_when: false
