---
- name: Ensure system is up to date
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install server kernel
  pacman:
    name:
      - linux-cachyos-server
      - linux-cachyos-server-headers
    state: present


- name: Install essential packages
  pacman:
    name:
      # - htop
      - iotop
      - ncdu
      - tmux
      # - vim
      # - git
      # - rsync
      - wget
      - curl
      # - python-pip
      # - python-setuptools
    state: present

- name: Configure NTP
  pacman:
    name: ntp
    state: present

- name: Enable and start NTP service
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: Set timezone
  timezone:
    name: America/New_York

# - name: Configure sysctl for performance
#   sysctl:
#     name: "{{ item.name }}"
#     value: "{{ item.value }}"
#     state: present
#     sysctl_file: /etc/sysctl.d/99-performance.conf
#   loop:
#     - { name: 'vm.swappiness', value: '10' }
#     - { name: 'vm.vfs_cache_pressure', value: '50' }
