---
- name: restart podman
  systemd:
    name: podman
    state: restarted
    daemon_reload: yes

- name: restart podman socket
  systemd:
    name: podman.socket
    state: restarted
    daemon_reload: yes